In [119]:
import numpy as np
import pandas as pd
from math import pi
import pandas as pd
import mca

In [ ]:
data = pd.read_csv('52900_alerts.csv', sep=';', header=0, index_col = 0)
datos = data.iloc[:30000]
datos = datos.drop(columns=['NUMBER', 'DATE_CASE','REF','SUBJET','PRODUCT','COUNT_CONCERN','COUNT_DESTIN','HAZARDS'])

In [164]:
x_dummy = mca.dummy(datos)
x_dummy 

CLASSIF                                                         \
        alert border rejection information information for attention   
0           1                0           0                         0   
1           0                0           0                         1   
2           0                1           0                         0   
3           0                1           0                         0   
4           1                0           0                         0   
5           1                0           0                         0   
6           0                0           0                         0   
7           0                0           0                         0   
8           1                0           0                         0   
9           0                0           0                         1   
10          0                1           0                         0   
11          0                1           0                         0   
12          0                0           0                         0   
13          0                1           0                         0   
14          1                0           0                         0   
15          0                1           0                         0   
16          0                1           0                         0   
17          1                0           0                         0   
18          0                1           0                         0   
19          0                0           0                         1   
20          1                0           0                         0   
21          0                1           0                         0   
22          0                1           0                         0   
23          0                1           0                         0   
24          0                1           0                         0   
25          0                1           0                         0   
26          0                1           0                         0   
27          1                0           0                         0   
28          1                0           0                         0   
29          1                0           0                         0   
...       ...              ...         ...                       ...   
29970       0                0           1                         0   
29971       0                1           0                         0   
29972       0                1           0                         0   
29973       0                0           1                         0   
29974       0                0           1                         0   
29975       0                0           1                         0   
29976       0                0           1                         0   
29977       0                0           1                         0   
29978       0                1           0                         0   
29979       0                0           1                         0   
29980       1                0           0                         0   
29981       0                1           0                         0   
29982       0                0           1                         0   
29983       0                0           1                         0   
29984       0                1           0                         0   
29985       0                0           1                         0   
29986       0                0           1                         0   
29987       0                1           0                         0   
29988       0                0           1                         0   
29989       0                0           1                         0   
29990       0                0           1                         0   
29991       0                0           1                         0   
29992       0                1           0    

In [165]:
mca_ben = mca.MCA(x_dummy) 

In [96]:
mca_ind = mca.MCA(x_dummy, benzecri=False)

In [167]:
print(mca_ben.fs_r(1))

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [158]:
print(mca_ben.fs_r(1).shape)

(30000, 1)


In [159]:
print(mca_ben.L)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


In [160]:
mca_ben.inertia

0

In [161]:
print(mca_ben.L.sum())

0


In [123]:
print(mca_ben.L)

[0.2218821  0.13706595 0.10865716 ... 0.00038074 0.00029755 0.00027689]


# No benzecri correlation

In [102]:
print(mca_ind.fs_r(1).shape)

(30000, 1541)


In [103]:
print(mca_ind.L)

[4.71382708e-01 3.70627887e-01 3.30061578e-01 ... 1.72703204e-02
 1.53087027e-03 1.73040185e-04]


In [104]:
mca_ind.inertia

172.33333333329352

In [105]:
print(mca_ind.L.sum())

172.33330073764344


In [ ]:
D = pd.get_dummies(datos)
D_t= D.transpose()

In [50]:
print(D.shape,D_t.shape)
B = np.matmul(D_t,D)
print(B.shape)
print(B)

(10, 18) (18, 10)
(18, 18)
[[4 0 0 0 0 4 0 4 1 1 0 0 2 0 4 0 0 0]
 [0 2 0 0 0 2 0 2 2 0 0 0 0 0 0 0 0 2]
 [0 0 2 0 0 2 1 1 1 0 1 0 0 1 0 0 1 0]
 [0 0 0 2 2 0 2 0 0 0 0 2 0 0 0 2 0 0]
 [0 0 0 2 2 0 2 0 0 0 0 2 0 0 0 2 0 0]
 [4 2 2 0 0 8 1 7 4 1 1 0 2 1 4 0 1 2]
 [0 0 1 2 2 1 3 0 1 0 0 2 0 1 0 2 0 0]
 [4 2 1 0 0 7 0 7 3 1 1 0 2 0 4 0 1 2]
 [1 2 1 0 0 4 1 3 4 0 0 0 0 1 1 0 0 2]
 [1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 2 2 0 2 0 0 0 0 2 0 0 0 2 0 0]
 [2 0 0 0 0 2 0 2 0 0 0 0 2 0 2 0 0 0]
 [0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0]
 [4 0 0 0 0 4 0 4 1 1 0 0 2 0 4 0 0 0]
 [0 0 0 2 2 0 2 0 0 0 0 2 0 0 0 2 0 0]
 [0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0]
 [0 2 0 0 0 2 0 2 2 0 0 0 0 0 0 0 0 2]]
